apiVersion: v1
kind: Template
metadata:
  name: dev-pipeline-template
  annotations:
    openshift.io/display-name: Application Pipeline (DEV)
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      pipeline: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      type: Git
      git:
        uri: http://gogs-gogs.192.168.64.36.nip.io/leandroberetta/openshift-pipelines.git
        ref: master
      contextDir: dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: APP
          value: ${PARAM_APP_NAME}
        - name: BASE_IMAGE
          value: ${PARAM_BASE_IMAGE}
        - name: ARTIFACTS_DIR
          value: ${PARAM_ARTIFACTS_DIR}
        - name: JENKINS_SLAVE_IMAGE
          value: ${PARAM_JENKINS_SLAVE_IMAGE}
        - name: COMPILE_COMMAND
          value: ${PARAM_COMPILE_COMMAND}
        - name: TEST_COMMAND
          value: ${PARAM_TEST_COMMAND}
        - name: CODE_ANALYSIS_COMMAND
          value: ${PARAM_CODE_ANALYSIS_COMMAND}
        - name: RELEASE_COMMAND
          value: ${PARAM_RELEASE_COMMAND}
        - name: TAG_IMAGE
          value: ${PARAM_TAG_IMAGE}
        - name: IMAGE
          value: ${PARAM_IMAGE_NAME}
        - name: TAG
          value: latest     
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
parameters:
- description: The application Git repository
  displayName: Application Git repository
  name: PARAM_GIT_REPO
  required: true
- description: The application Git branch
  displayName: Application Git branch
  name: PARAM_GIT_BRANCH
  value: master
- description: The application name
  displayName: Application name
  name: PARAM_APP_NAME
  required: true
- description: The application base image
  displayName: Application base image
  name: PARAM_BASE_IMAGE
  value: redhat-openjdk18-openshift:1.2
  required: true
- description: The folder that points to the application binaries or files
  displayName: Application binaries
  name: PARAM_ARTIFACTS_DIR
  required: true
  value: "./target"
- description: The application's compile command
  displayName: Compile command
  name: PARAM_COMPILE_COMMAND
  required: true
  value: "mvn package -DskipTests"
- description: The application's test command
  displayName: Test command
  name: PARAM_TEST_COMMAND
  required: true
  value: "none"
- description: The application's code analysis command
  displayName: Code analysis command
  name: PARAM_CODE_ANALYSIS_COMMAND
  required: true
  value: "none"
- description: The application's release command
  displayName: Release command
  name: PARAM_RELEASE_COMMAND
  required: true
  value: "none"
- description: The Jenkins slave image to compile the application
  displayName: Jenkins slave image
  name: PARAM_JENKINS_SLAVE_IMAGE
  required: true
  value: maven
- description: Whether to tag the generated image or not
  displayName: Tag image
  name: PARAM_TAG_IMAGE
  value: "false"
  required: true
- description: Image name
  displayName: Image name
  name: IMAGE_NAME
