apiVersion: v1
kind: Template
metadata:
  name: dev-pipelines-template
  annotations:
    openshift.io/display-name: Application Pipelines (Dev)
    iconClass: fa fa-code
    description: Templates to generate several pipelines for development. 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}-develop
    name: ${PARAM_APP_NAME}-develop-pipeline
  spec:
    source:
      type: Git
      git:
        uri: http://gogs-gogs.192.168.64.37.nip.io/leandroberetta/openshift-pipelines.git
        ref: master
      contextDir: dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: APP_NAME
          value: ${PARAM_APP_NAME}-develop
        - name: APP_TEMPLATE
          value: ${PARAM_APP_TEMPLATE}
        - name: BASE_IMAGE
          value: ${PARAM_BASE_IMAGE}
        - name: ARTIFACTS_DIR
          value: ${PARAM_ARTIFACTS_DIR}
        - name: JENKINS_SLAVE_IMAGE
          value: ${PARAM_JENKINS_SLAVE_IMAGE}
        - name: COMPILE_COMMAND
          value: ${PARAM_COMPILE_COMMAND}
        - name: TEST_COMMAND
          value: ${PARAM_TEST_COMMAND}
        - name: CODE_ANALYSIS_COMMAND
          value: ${PARAM_CODE_ANALYSIS_COMMAND}
        - name: RELEASE_COMMAND
          value: ${PARAM_RELEASE_COMMAND}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}-release
    name: ${PARAM_APP_NAME}-release-pipeline
  spec:
    source:
      type: Git
      git:
        uri: http://gogs-gogs.192.168.64.37.nip.io/leandroberetta/openshift-pipelines.git
        ref: master
      contextDir: dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: APP_NAME
          value: ${PARAM_APP_NAME}-release
        - name: IMAGE_NAME
          value: ${PARAM_APP_NAME}
        - name: APP_TEMPLATE
          value: ${PARAM_APP_TEMPLATE}
        - name: BASE_IMAGE
          value: ${PARAM_BASE_IMAGE}
        - name: ARTIFACTS_DIR
          value: ${PARAM_ARTIFACTS_DIR}
        - name: JENKINS_SLAVE_IMAGE
          value: ${PARAM_JENKINS_SLAVE_IMAGE}
        - name: COMPILE_COMMAND
          value: ${PARAM_COMPILE_COMMAND}
        - name: TEST_COMMAND
          value: ${PARAM_TEST_COMMAND}
        - name: CODE_ANALYSIS_COMMAND
          value: ${PARAM_CODE_ANALYSIS_COMMAND}
        - name: RELEASE_COMMAND
          value: ${PARAM_RELEASE_COMMAND}
        - name: MANUAL_TAG
          value: "true"
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
parameters:
- description: The application's Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The application's branch for development
  displayName: Dev Branch
  name: PARAM_GIT_BRANCH
  value: develop
  required: true
- description: The name for the application
  displayName: Application name
  name: PARAM_APP_NAME
  required: true
- description: The template file (YAML) to create the application's objects
  displayName: Template File
  name: PARAM_APP_TEMPLATE
  required: true
- description: The base image for the application (S2I Binary will be used)
  displayName: S2I (Binary) Base Image
  name: PARAM_BASE_IMAGE
  value: redhat-openjdk18-openshift:1.2
  required: true
- description: The folder that points to the application binaries or files
  displayName: Application Binaries
  name: PARAM_ARTIFACTS_DIR
  required: true
  value: "./target"
- description: The application's compile command (if not required, leave none)
  displayName: Compile Command
  name: PARAM_COMPILE_COMMAND
  required: true
  value: "mvn package -DskipTests"
- description: The application's test command (if not required, leave none)
  displayName: Test Command
  name: PARAM_TEST_COMMAND
  required: true
  value: none
- description: The application's code analysis command (if not required, leave none)
  displayName: Code Analysis Command
  name: PARAM_CODE_ANALYSIS_COMMAND
  required: true
  value: none
- description: The application's release command (if not required, leave none)
  displayName: Release Command
  name: PARAM_RELEASE_COMMAND
  required: true
  value: none
- description: The Jenkins slave image that will be used to compile the application (maven, nodejs or custom...)
  displayName: Jenkins Slave Image
  name: PARAM_JENKINS_SLAVE_IMAGE
  required: true
  value: maven