apiVersion: v1
kind: Template
metadata:
  name: hello-config-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}
  data:
    hello.environment: prod
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: hello-service.192.168.64.162.nip.io
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: hello-service