apiVersion: v1
kind: Template
metadata:
  name: prod-pipeline-template
  annotations:
    openshift.io/display-name: Application (PROD)
    iconClass: fa fa-code
    description: Template to generate an application and its pipeline.
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      type: Git
      sourceSecret:
        name: git-secret
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: environments/prod
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${PARAM_APP_NAME}
        - name: APP_TEMPLATE_FILE
          value: ${PARAM_APP_TEMPLATE_FILE}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_SECRET
          value: git-secret
        - name: SRC_PROJECT
          value: ${PARAM_SRC_PROJECT}     
        - name: DST_PROJECT
          value: ${PARAM_DST_PROJECT}
        - name: APPROVAL_GROUP
          value: prod-approvers
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The application name to deploy (must exists in source project)
  displayName: Application Name
  name: PARAM_APP_NAME
  required: true
- description: The application template file to create the application
  displayName: Application Template File
  name: PARAM_APP_TEMPLATE_FILE
  required: true
- description: The application Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The source project for image and objects promotion
  displayName: Source Project
  name: PARAM_SRC_PROJECT
  required: true
- description: The destination project for image and objects promotion
  displayName: Destination Project
  name: PARAM_DST_PROJECT
  required: true
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"