apiVersion: v1
kind: Template
metadata:
  name: prod-pipeline-template
  annotations:
    openshift.io/display-name: Application Pipeline (Prod)
    iconClass: fa fa-code
    description: Template to generate a production pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP}
    name: ${PARAM_APP}-pipeline
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: environments/prod
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP
          value: ${PARAM_APP}
        - name: APP_TEMPLATE_FILE
          value: ${PARAM_APP_TEMPLATE_FILE}
        - name: SRC_PROJECT
          value: ${PARAM_SRC_PROJECT}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_SECRET
          value: ${PARAM_GIT_SECRET}
        - name: APPROVAL_GROUP
          value: prod-approvers
        - name: COMMONS_API_URL
          value: https://github.com/redhatcsargentina/openshift-pipelines/raw/master/api/commons.groovy
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The name for the application to deploy (must exists in source project)
  displayName: Application Name
  name: PARAM_APP
  required: true
- description: The application template file (YAML) to create the application objects
  displayName: Application Template File
  name: PARAM_APP_TEMPLATE_FILE
  required: true
- description: The application Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The Git credentials (must be the name of an OpenShift Secret or "none" if credentials are not needed)
  displayName: Git Credentials
  name: PARAM_GIT_SECRET
  value: none
  required: true
- description: The source project for image and objects promotion
  displayName: Source Project
  name: PARAM_SRC_PROJECT
  required: true
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"