apiVersion: v1
kind: Template
metadata:
  name: hello-config-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}-config
  data:
    hello.environment: dev2
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: hello-service