apiVersion: v1
kind: Template
metadata:
  name: prod-pipeline-template
  annotations:
    openshift.io/display-name: Application Pipeline (Prod)
    iconClass: fa fa-code
    description: Template to generate a production pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: test
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${PARAM_APP_NAME}
        - name: APP_IMAGE
          value: ${PARAM_APP_NAME}
        - name: PROJECT_NAME
          value: test  
        - name: APP_TEMPLATE_NAME
          value: ${PARAM_APP_TEMPLATE_NAME}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The name for the application
  displayName: Application Name
  name: PARAM_APP_NAME
- description: The template to create the application's objects
  displayName: Template Name
  name: PARAM_APP_TEMPLATE_NAME
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"