apiVersion: v1
kind: Template
metadata:
  name: prod-pipeline-template
  annotations:
    openshift.io/display-name: Application Pipeline (Prod)
    iconClass: fa fa-code
    description: Template to generate a production pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: prod
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${PARAM_APP_NAME}
        - name: APP_IMAGE
          value: ${PARAM_APP_NAME}
        - name: SRC_PROJECT_NAME
          value: ${PARAM_SRC_PROJECT_NAME}
        - name: DST_PROJECT_NAME
          value: ${PARAM_DST_PROJECT_NAME}
        - name: APP_TEMPLATE_NAME
          value: ${PARAM_APP_TEMPLATE_NAME}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The name for the application
  displayName: Application Name
  name: PARAM_APP_NAME
  required: true
- description: The template to create the application's objects
  displayName: Template Name
  name: PARAM_APP_TEMPLATE_NAME
  required: true
- description: The source project for image and objects promotion
  displayName: Source Project
  name: PARAM_SRC_PROJECT_NAME
  required: true
  value: test
- description: The destination project for image and objects promotion
  displayName: Destination Project
  name: PARAM_DST_PROJECT_NAME
  required: true
  value: prod
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"