apiVersion: v1
kind: Template
metadata:
  name: java-pipeline
  annotations:
    openshift.io/display-name: Java Pipeline
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APPLICATION}
    name: ${PARAM_APPLICATION}-pipeline
  spec:
    source:
      git:
        uri: "https://github.com/leandroberetta/openshift-pipelines.git"
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APPLICATION
          value: ${PARAM_APP}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: TECH
          value: maven
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The application name
  displayName: Application Name
  name: PARAM_APPLICATION
  required: true
- description: The Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The Git branch
  displayName: Git Branch
  name: PARAM_GIT_BRANCH
  required: true
  value: master
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"