apiVersion: v1
kind: Template
metadata:
  name: openshift-hello-world
  annotations:
    openshift.io/display-name: Hello World
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}-pipeline
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${APP_NAME}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
      type: JenkinsPipeline
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          name: ${APP_NAME}
          env:
          - name: HELLO_STRING
            value: ${HELLO_STRING}
          - name: HELLO_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                key: hello.environment
                name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
    triggers: 
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata: 
    name: ${APP_NAME}
  data:
    hello.environment: ${ENVIRONMENT}
parameters:
- description: Application name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: openshift-hello-world
- description: Git repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
  value: https://github.com/leandroberetta/openshift-cicd-demo.git
- description: Git branch
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
  value: master
- name: HELLO_STRING
  displayName: Hello World Message
  description: Hello World Message
  required: true
  value: "Hello World from OpenShift!"
- name: ENVIRONMENT
  displayName: Environment
  description: Environment
  required: true
  value: DEV