apiVersion: v1
kind: Template
metadata:
  name: dev-pipelines-template
  annotations:
    openshift.io/display-name: Application Pipelines (Dev)
    iconClass: fa fa-code
    description: Templates to generate the pipelines for an application development. 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP}-develop-pipeline
    name: ${PARAM_APP}-develop-pipeline
  spec:
    source:
      type: Git
      sourceSecret:
        name: github
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: environments/dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_SECRET
          value: ${PARAM_GIT_SECRET}
        - name: APP
          value: ${PARAM_APP}-develop
        - name: APP_TEMPLATE_FILE
          value: ${PARAM_APP_TEMPLATE_FILE}
        - name: BASE_IMAGE
          value: ${PARAM_BASE_IMAGE}
        - name: ARTIFACTS_DIR
          value: ${PARAM_ARTIFACTS_DIR}
        - name: JENKINS_AGENT
          value: ${PARAM_JENKINS_AGENT}
        - name: COMPILE_COMMAND
          value: ${PARAM_COMPILE_COMMAND}
        - name: TEST_COMMAND
          value: ${PARAM_TEST_COMMAND}
        - name: CODE_ANALYSIS_COMMAND
          value: ${PARAM_CODE_ANALYSIS_COMMAND}
        - name: RELEASE_COMMAND
          value: ${PARAM_RELEASE_COMMAND}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP}-release-pipeline
    name: ${PARAM_APP}-release-pipeline
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: environments/dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_SECRET
          value: ${PARAM_GIT_SECRET}
        - name: APP
          value: ${PARAM_APP}
        - name: IMAGE
          value: ${PARAM_APP}
        - name: APP_TEMPLATE_FILE
          value: ${PARAM_APP_TEMPLATE_FILE}
        - name: BASE_IMAGE
          value: ${PARAM_BASE_IMAGE}
        - name: ARTIFACTS_DIR
          value: ${PARAM_ARTIFACTS_DIR}
        - name: JENKINS_AGENT
          value: ${PARAM_JENKINS_AGENT}
        - name: COMPILE_COMMAND
          value: ${PARAM_COMPILE_COMMAND}
        - name: TEST_COMMAND
          value: ${PARAM_TEST_COMMAND}
        - name: CODE_ANALYSIS_COMMAND
          value: ${PARAM_CODE_ANALYSIS_COMMAND}
        - name: RELEASE_COMMAND
          value: ${PARAM_RELEASE_COMMAND}
        - name: MANUAL_TAG
          value: "true"
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The name for the application
  displayName: Application Name
  name: PARAM_APP
  required: true
- description: The application template file (YAML) to create the application objects
  displayName: Application Template File
  name: PARAM_APP_TEMPLATE_FILE
  required: true
- description: The application Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The application branch for development
  displayName: Git Branch
  name: PARAM_GIT_BRANCH
  value: develop
  required: true
- description: The Git credentials (must be the name of an OpenShift Secret or "none" if credentials are not needed)
  displayName: Git Credentials
  name: PARAM_GIT_SECRET
  required: true
- description: The base image for the application (S2I Binary will be used)
  displayName: S2I (Binary) Base Image
  name: PARAM_BASE_IMAGE
  value: redhat-openjdk18-openshift:1.2
  required: true
- description: The folder that points to the application binaries or files
  displayName: Application Binaries
  name: PARAM_ARTIFACTS_DIR
  value: "./target"
- description: The application compile command (if not required, leave "none")
  displayName: Compile Command
  name: PARAM_COMPILE_COMMAND
  required: true
  value: "mvn package -DskipTests"
- description: The application test command (if not required, leave "none")
  displayName: Test Command
  name: PARAM_TEST_COMMAND
  required: true
  value: none
- description: The application code analysis command (if not required, leave "none")
  displayName: Code Analysis Command
  name: PARAM_CODE_ANALYSIS_COMMAND
  required: true
  value: none
- description: The application release command (if not required, leave "none")
  displayName: Release Command
  name: PARAM_RELEASE_COMMAND
  required: true
  value: none
- description: The Jenkins agent image that will be used to compile the application (maven, nodejs or custom)
  displayName: Jenkins Agent Image
  name: PARAM_JENKINS_AGENT
  required: true
  value: maven
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"